language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "nUIp32Ymad68oCRgky1NNR74kK28dJIhYTsIO53CkRO47jS48UU5fvE8F6Cp+P0RbwYRFFzf8qvGXhmZMjjaM0Pidskle7XBTab9YptuG+zUq5rAjt3IbVgpKe8Eu7IHh2oQYTnXcvzUErWG4DbntOoy21v1OJlOIN+by9ozriYtzvBlQ23FVELlrg4PFyhoaHffz/pI1HTGtC8qXU3PPRSEvNnWSY0b6AEoTxakDhLZhCW5VmWmnSt4Xzmn1qM4oj0eaHOMPNhnZP4fVQefhRr6qpC6Z7a0xg/18ig9wVF7J24+WQ8sxdYkw9U0umEXglzBdkaLWlpndkj12mel79z6SnMzmqYsDR4FfwLJwkDvHCi4Nh4C7ErpWPIy7180KdNXTBRjosH5AyegSAJt5dXEcwBJMxhkjCmRQNyfnB/66zC36El8Q1ZSncFGjUo3CYDY/kvsuYnAHjAO1WsJbKaLv8UIVY9UOqbwinvKFocREfUvkcB4o6WptxBQhd+UOQ0tjkbo7dC1WNCps1bn77GUimeqL0jF82BFzYLGsSB/s92m+bkCl3SgI86ZobwVBzPUn22bz0S+AGxM7y/dEM5kbg9GpxnEA4CXtQxrQHm1WceRlMxZL9FPv4QAFBSNT6ovrH14TwwIYQPuCzF5xAHrsZMVKItUffdQzm7UJ5g="

