version: 1.0.{build}

cache:
  - C:\Users\appveyor\.m2\repository

install:
  - set MAVEN_VERSION=3.2.5
  - mkdir C:\bin
  - curl --output C:\bin\apache-maven-%MAVEN_VERSION%-bin.zip -L -sS --retry 3 --retry-delay 10 "http://www.apache.org/dyn/closer.cgi?action=download&filename=maven/maven-3/%MAVEN_VERSION%/binaries/apache-maven-%MAVEN_VERSION%-bin.zip"
  - unzip -q -d C:\bin C:\bin\apache-maven-%MAVEN_VERSION%-bin.zip
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

build_script:
  - ps: ./appveyor.ps1

test: off

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
